name: Render LINE Bot 每日下班提醒

on:
  schedule:
    - cron: '20 9 * * 1-5'  # 每週一至週五台灣時間 17:20（UTC 時區為 +0）
  workflow_dispatch:

jobs:
  send_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: 呼叫 Render 上的 /work-reminder 路由
        run: curl -X GET https://work-report-reminder.onrender.com/work-reminder
